CREATE TABLE dbo.NewTestTable
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(300) NOT NULL,
    Description NVARCHAR(500) NULL,
    IsActive BIT NOT NULL DEFAULT (1),
    CreatedDate DATETIME2 NOT NULL DEFAULT (GETDATE())
);

ALTER TABLE dbo.NewTestTable
ADD POProductItemId BIGINT NULL;