CREATE TABLE [dbo].[Orders_Trigger_Log] (
    [ID]                           BIGINT             IDENTITY (1, 1) NOT NULL,
    [OldGSTType]                   BIT                NULL,
    [NewGSTType]                   BIT                NULL,
    [OrderId]                      BIGINT             NOT NULL,
    [OrderNo]                      VARCHAR (20)       NOT NULL,
    [CustomerID]                   BIGINT             NOT NULL,
    [RefferedBy]                   BIGINT             NULL,
    [GrossTotal]                   NUMERIC (18, 2)    NOT NULL,
    [Discount]                     NUMERIC (18, 2)    NOT NULL,
    [TotalAmount]                  NUMERIC (18, 2)    NOT NULL,
    [TotalAmt]                     NUMERIC (18, 2)    NOT NULL,
    [AmountBeforeGST]              NUMERIC (18, 2)    CONSTRAINT [df_Orders_Trigger_Log_AmountBeforeGST] DEFAULT ((0)) NULL,
    [CGSTAmount]                   NUMERIC (18, 2)    CONSTRAINT [df_Orders_Trigger_Log_CGSTAmount] DEFAULT ((0)) NULL,
    [SGSTAmount]                   NUMERIC (18, 2)    CONSTRAINT [df_Orders_Trigger_Log_SGSTAmount] DEFAULT ((0)) NULL,
    [GSTTaxAmount]                 NUMERIC (18, 2)    NOT NULL,
    [AdvanceAmount]                NUMERIC (9, 2)     NOT NULL,
    [DeliveryDate]                 DATE               NULL,
    [Comments]                     NVARCHAR (MAX)     NULL,
    [IsFreeDelivery]               BIT                CONSTRAINT [DF_Orders_Trigger_Log_IsFreeDelivery] DEFAULT ((0)) NOT NULL,
    [Status]                       INT                CONSTRAINT [DF__Orders_Trigger_Log__Status__30242045] DEFAULT ((1)) NOT NULL,
    [TenantId]                     INT                NOT NULL,
    [InquiryExpirationDate]        DATETIMEOFFSET (7) NULL,
    [DeliveryCharges]              NUMERIC (18, 2)    NULL,
    [ApprovedDate]                 DATETIMEOFFSET (7) NULL,
    [TentativeDeliveryDate]        DATE               NULL,
    [OrderType]                    SMALLINT           CONSTRAINT [DF__Orders_Trigger_Log__OrderTyp__5AD97420] DEFAULT ((1)) NOT NULL,
    [OfferDiscount]                NUMERIC (18, 2)    CONSTRAINT [df_Orders_Trigger_Log_OfferAmount] DEFAULT ((0)) NULL,
    [CreatedBy]                    INT                NOT NULL,
    [CreatedDate]                  DATETIMEOFFSET (7) CONSTRAINT [DF__Orders_Trigger_Log__CreatedD__320C68B7] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CreatedUTCDate]               DATETIME           CONSTRAINT [DF__Orders_Trigger_Log__CreatedU__33008CF0] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]                    INT                NULL,
    [UpdatedDate]                  DATETIMEOFFSET (7) NULL,
    [UpdatedUTCDate]               DATETIME           NULL,
    [InquiryLastUpdatedDate]       DATETIMEOFFSET (7) NULL,
    [LabelId]                      BIGINT             NULL,
    [GSTType]                      BIT                DEFAULT ((0)) NOT NULL,
    [LumpsumDiscount]              NUMERIC (18)       NULL,
    [DeliveryAmount]               NUMERIC (9)        NULL,
    [DeliveryAmountCollectionType] INT                NULL,
    [DeliveryCharge]               TINYINT            NULL,
    [LocationID]                   BIGINT             NULL,
    [SalesmanId]                   INT                NOT NULL,
    [InteriorCommissionPer]        NUMERIC (5, 2)     DEFAULT ((0)) NULL,
    [IsSyncWithTally]              BIT                DEFAULT ((0)) NOT NULL,
    [IsBackOrder]                  BIT                DEFAULT ((0)) NOT NULL,
    [SalesmanCommissionPer]        NUMERIC (5, 2)     NULL,
    [IsFlagged]                    BIT                DEFAULT ((0)) NULL,
    [IsPinned]                     BIT                DEFAULT ((0)) NULL,
    [ViewInquiryImage]             INT                DEFAULT ((1)) NOT NULL,
    [IsArchive]                    BIT                DEFAULT ((0)) NOT NULL,
    [TRGCreatedDate]               DATETIMEOFFSET (7) CONSTRAINT [DF__Orders_Trigger_Log__TRGCreatedD__320C68B7] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [TRGCreatedUTCDate]            DATETIME           CONSTRAINT [DF__Orders_Trigger_Log__TRGCreatedU__33008CF0] DEFAULT (getutcdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

