CREATE TABLE [dbo].[Tenants] (
    [TenantId]                             INT                IDENTITY (1, 1) NOT NULL,
    [TenantName]                           VARCHAR (150)      NOT NULL,
    [FirstName]                            VARCHAR (50)       NOT NULL,
    [LastName]                             VARCHAR (50)       NOT NULL,
    [EmailId]                              VARCHAR (50)       NOT NULL,
    [PhoneNumber]                          VARCHAR (15)       NOT NULL,
    [LogoPath]                             VARCHAR (500)      NULL,
    [StreetAddress1]                       VARCHAR (150)      NOT NULL,
    [StreetAddress2]                       VARCHAR (150)      NULL,
    [Landmark]                             VARCHAR (150)      NULL,
    [City]                                 VARCHAR (100)      NOT NULL,
    [State]                                VARCHAR (100)      NOT NULL,
    [Pincode]                              VARCHAR (6)        NOT NULL,
    [IsDeleted]                            BIT                CONSTRAINT [DF__Tenants__IsDelet__625A9A57] DEFAULT ((0)) NOT NULL,
    [CreatedBy]                            INT                NOT NULL,
    [CreatedDate]                          DATETIMEOFFSET (7) CONSTRAINT [DF__Tenants__Created__634EBE90] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CreatedUTCDate]                       DATETIME           CONSTRAINT [DF__Tenants__Created__6442E2C9] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]                            INT                NULL,
    [UpdatedDate]                          DATETIMEOFFSET (7) NULL,
    [UpdatedUTCDate]                       DATETIME           NULL,
    [WebsiteURL]                           VARCHAR (250)      NULL,
    [TwitterURL]                           VARCHAR (250)      NULL,
    [FacebookURL]                          VARCHAR (250)      NULL,
    [InstagramURL]                         VARCHAR (250)      NULL,
    [GSTNo]                                VARCHAR (20)       NULL,
    [ProductWSPPercentage]                 NUMERIC (5, 2)     NULL,
    [ProductRSPPercentage]                 NUMERIC (5, 2)     NULL,
    [ArchitectDiscount]                    NUMERIC (5, 2)     NULL,
    [FabricRSPPercentage]                  NUMERIC (5, 2)     NULL,
    [FabricWSPPercentage]                  NUMERIC (5, 2)     NULL,
    [AmountRoundMultiple]                  INT                NULL,
    [SendOTP]                              BIT                CONSTRAINT [DF__Tenants__SendOTP__0C70CFB4] DEFAULT ((0)) NULL,
    [InquiryExpirationDays]                INT                CONSTRAINT [DF__Tenants__Inquiry__15FA39EE] DEFAULT ((10)) NOT NULL,
    [NotificationEmail]                    VARCHAR (100)      NULL,
    [EnableEmailNotification]              BIT                NULL,
    [EnableSMSNotification]                BIT                NULL,
    [EnableWhatsappNotification]           BIT                NULL,
    [GSTType]                              BIT                DEFAULT ((0)) NOT NULL,
    [IsAutoManufacture]                    BIT                DEFAULT ((0)) NOT NULL,
    [MasterOTP]                            VARCHAR (4)        DEFAULT ('0000') NOT NULL,
    [CheckRawMaterialStock]                BIT                DEFAULT ((0)) NOT NULL,
    [CheckProductStock]                    BIT                DEFAULT ((0)) NOT NULL,
    [InstallationCharges]                  DECIMAL (18, 2)    CONSTRAINT [DF_Tenants_InstallationCharge] DEFAULT ((0)) NULL,
    [RecurringCharges]                     DECIMAL (18, 2)    NULL,
    [TenantInfoId]                         INT                NULL,
    [IsAutoSendCustomerFeedback]           BIT                DEFAULT ((0)) NOT NULL,
    [RazorPayKeyId]                        VARCHAR (500)      NULL,
    [RazorPaySecretKey]                    VARCHAR (500)      NULL,
    [EveryoneEmail]                        VARCHAR (50)       NULL,
    [Greetinglogo]                         VARCHAR (MAX)      NULL,
    [IsSendGreeting]                       BIT                DEFAULT ((0)) NULL,
    [ViewInquiryImage]                     VARCHAR (50)       CONSTRAINT [DF__Tenants__ViewInq__63E3BB6D] DEFAULT ((1)) NULL,
    [AllowLeadAddress]                     BIT                DEFAULT ((0)) NOT NULL,
    [VerifyingCustomer]                    BIT                DEFAULT ((0)) NOT NULL,
    [CustomerScanProduct]                  BIT                DEFAULT ((0)) NOT NULL,
    [IsPrintProductBanner]                 BIT                DEFAULT ((0)) NOT NULL,
    [IsVendorEmailNotification]            BIT                DEFAULT ((0)) NOT NULL,
    [IsVendorSMSNotification]              BIT                DEFAULT ((0)) NOT NULL,
    [IsVendorWhatsappNotification]         BIT                DEFAULT ((0)) NOT NULL,
    [IsSendWelcomeMail]                    BIT                DEFAULT ((0)) NOT NULL,
    [AllowCustomerAddress]                 BIT                DEFAULT ((0)) NOT NULL,
    [IsOrderHardDelete]                    BIT                DEFAULT ((0)) NOT NULL,
    [ReferalCode]                          VARCHAR (10)       DEFAULT (left(CONVERT([varchar](36),newid()),(6))) NOT NULL,
    [DisplayGSTOrNot]                      BIT                DEFAULT ((1)) NULL,
    [IsProductWatermark]                   BIT                DEFAULT ((0)) NOT NULL,
    [IsDemo]                               BIT                DEFAULT ((0)) NOT NULL,
    [IsBeforeGST]                          BIT                DEFAULT ((1)) NOT NULL,
    [AttendanceRadiusVerification]         BIT                DEFAULT ((0)) NOT NULL,
    [RadiusinKilometers]                   NUMERIC (4, 2)     NULL,
    [ProductPriceConfiguration]            BIT                DEFAULT ((1)) NOT NULL,
    [DeactiveDate]                         DATETIME           NULL,
    [AllowDuplicateProductModelNo]         BIT                DEFAULT ((0)) NOT NULL,
    [Currency]                             VARCHAR (50)       NULL,
    [ViewPriceOnQuotation]                 BIT                DEFAULT ((1)) NOT NULL,
    [AllowPaymentNotification]             BIT                DEFAULT ((1)) NOT NULL,
    [ResetQuotation]                       INT                DEFAULT ((5)) NOT NULL,
    [OrderPDFOrientation]                  BIT                DEFAULT ((0)) NOT NULL,
    [DisplayStockToDealer]                 BIT                DEFAULT ((0)) NOT NULL,
    [MakeAddressMandatory]                 BIT                DEFAULT ((0)) NOT NULL,
    [IsRestrictDeliveryWithoutFullPayment] BIT                DEFAULT ((0)) NOT NULL,
    [AppBundleId]                          VARCHAR (50)       DEFAULT ('io.ionic.TanyoERP') NOT NULL,
    [OrgWorkingHours]                      VARCHAR (10)       DEFAULT ('09:00') NOT NULL,
    [SubDomain]                            VARCHAR (20)       NULL,
    [FullAddress]                          VARCHAR (500)      NULL,
    [Country]                              VARCHAR (100)      NULL,
    [IsPaymentDue]                         BIT                DEFAULT ((0)) NOT NULL,
    [PaymentStatusMessage]                 VARCHAR (500)      DEFAULT ('Your payment is pending. Please pay to continue using the service.') NOT NULL,
    CONSTRAINT [PK_Tenants] PRIMARY KEY CLUSTERED ([TenantId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [UQ_Tenant_ReferalCode] UNIQUE NONCLUSTERED ([ReferalCode] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IX_Tenants_IsDeleted_CreatedBy_CreatedDate]
    ON [dbo].[Tenants]([IsDeleted] ASC, [CreatedBy] ASC, [CreatedDate] ASC)
    INCLUDE([FirstName], [LastName], [LogoPath], [GSTNo], [GSTType]);


GO

