CREATE TABLE [dbo].[WebhookResponse] (
    [WebhookResponseId] BIGINT             IDENTITY (1, 1) NOT NULL,
    [Entity]            NVARCHAR (50)      NULL,
    [AccountId]         NVARCHAR (50)      NULL,
    [Event]             NVARCHAR (50)      NULL,
    [PaymentId]         NVARCHAR (50)      NULL,
    [Amount]            NVARCHAR (50)      NULL,
    [Currency]          NVARCHAR (50)      NULL,
    [BaseAmount]        NVARCHAR (50)      NULL,
    [Status]            NVARCHAR (50)      NULL,
    [PaymentOrderId]    NVARCHAR (50)      NULL,
    [InvoiceId]         NVARCHAR (50)      NULL,
    [International]     BIT                NULL,
    [method]            NVARCHAR (50)      NULL,
    [Captured]          BIT                NULL,
    [Description]       NVARCHAR (500)     NULL,
    [CardId]            NVARCHAR (50)      NULL,
    [Bank]              NVARCHAR (50)      NULL,
    [Wallet]            NVARCHAR (50)      NULL,
    [VPA]               NVARCHAR (50)      NULL,
    [Email]             NVARCHAR (50)      NULL,
    [ContactNo]         NVARCHAR (15)      NULL,
    [Fee]               NVARCHAR (50)      NULL,
    [Tax]               NVARCHAR (50)      NULL,
    [ErrorCode]         NVARCHAR (50)      NULL,
    [ErrorDescription]  NVARCHAR (50)      NULL,
    [ErrorReason]       NVARCHAR (50)      NULL,
    [ErrorSoure]        NVARCHAR (50)      NULL,
    [ErrorStep]         NVARCHAR (50)      NULL,
    [TokenId]           NVARCHAR (50)      NULL,
    [BankTransactionId] NVARCHAR (50)      NULL,
    [TransactionId]     NVARCHAR (50)      NULL,
    [PayerAccountType]  NVARCHAR (50)      NULL,
    [Flow]              NVARCHAR (50)      NULL,
    [AuthCode]          NVARCHAR (50)      NULL,
    [RRN]               NVARCHAR (50)      NULL,
    [CardEMI]           BIT                NULL,
    [CardEntity]        NVARCHAR (50)      NULL,
    [CardIIN]           NVARCHAR (50)      NULL,
    [CardIssuer]        NVARCHAR (50)      NULL,
    [CardLast4]         NVARCHAR (50)      NULL,
    [CardName]          NVARCHAR (50)      NULL,
    [CardNetwork]       NVARCHAR (50)      NULL,
    [CardSubType]       NVARCHAR (50)      NULL,
    [CardType]          NVARCHAR (50)      NULL,
    [CreatedDate]       DATETIMEOFFSET (7) NULL,
    [CreatedUTCDate]    DATETIME           NULL,
    CONSTRAINT [PK_WebhookResponse] PRIMARY KEY CLUSTERED ([WebhookResponseId] ASC)
);


GO

